version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "11:00"
    ignore:
      # For axios, ignore major updates
      - dependency-name: "axios"
        update-types:
          ["version-update:semver-major"]
      # For dayjs, ignore major and minor updates
      - dependency-name: "dayjs"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      # For react-pdf / phone, ignore all updates
      - dependency-name: "react-pdf"
      - dependency-name: "phone"
    groups:
      file-saver:
        applies-to: version-updates
        patterns:
        # "*file-saver"
        - "file-saver"
        - "@types/file-saver"
        update-types:
        - "minor"
        - "patch"
